### ISSUE TITLE
How can I get *.modal file?

### ISSUE THREAD

**Issue by bewithdhanu** [Adityaojas/sudoku-solver#1]
I am unable to generate a modal file, how can I generate this modal file, here are the logs sudoku_solver.py
```
C:\Users\bewit\miniconda3\python.exe C:/Users/bewit/Downloads/sudoku-solver-master/sudoku_solver.py
Traceback (most recent call last):
  File "C:/Users/bewit/Downloads/sudoku-solver-master/sudoku_solver.py", line 14, in <module>
    model = load_model('model/best_model_lenet_aug_loss_3.model')
  File "C:\Users\bewit\miniconda3\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 149, in load_model
    loader_impl.parse_saved_model(filepath)
  File "C:\Users\bewit\miniconda3\lib\site-packages\tensorflow_core\python\saved_model\loader_impl.py", line 83, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: model/best_model_lenet_aug_loss_3.model/{saved_model.pbtxt|saved_model.pb}

Process finished with exit code 1
```

**Comment by bewithdhanu** [comment]
I ran this program by commenting` model = load_model('model/best_model_lenet_aug_loss_3.model')` 
it showing wrong solutions 
![sudoku_screenshot_19 07 2020](https://user-images.githubusercontent.com/19368533/87872981-170d7480-c9db-11ea-8a2c-d4607c367b3c.png)

**Comment by bewithdhanu** [comment]
I have taken some sample sudoku puzzles in `model/data` folder as in below Image 
![image](https://user-images.githubusercontent.com/19368533/87873008-6784d200-c9db-11ea-8cd4-ce3a0772dc53.png)

Then I ran the program `model\train_char74K.py`, but it is throwing below log
```
C:\Users\bewit\miniconda3\python.exe C:/Users/bewit/Downloads/sudoku-solver-master/model/train_char74K.py
2020-07-19 16:13:50.304915: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX
WARNING:tensorflow:From C:/Users/bewit/Downloads/sudoku-solver-master/model/train_char74K.py:64: Model.fit_generator (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
Please use Model.fit, which supports generators.
WARNING:tensorflow:sample_weight modes were coerced from
  ...
    to  
  ['...']
WARNING:tensorflow:sample_weight modes were coerced from
  ...
    to  
  ['...']
Train for 0.0625 steps, validate for 1 steps
Epoch 1/80
2020-07-19 16:13:51.588092: F .\tensorflow/core/framework/tensor.h:781] Check failed: NDIMS == new_sizes.size() (2 vs. 1)

Process finished with exit code -1073740791 (0xC0000409)

```

**Comment by avasid** [comment]
@bewithdhanu you need Chars74k dataset for digit recognition.
Try here, http://www.ee.surrey.ac.uk/CVSSP/demos/chars74k/#download

**Comment by bewithdhanu** [comment]
@avasid I have downloaded EnglishImg from the mentioned link used it like below
`model = load_model('model/EnglishImg')`
even though I am having some issue, I am not much familiar with python, can you explain what to do with that char74k dataset to run this program
```
C:\Users\bewit\miniconda3\python.exe C:/Users/bewit/Downloads/sudoku-solver-master/sudoku_solver.py
Traceback (most recent call last):
  File "C:/Users/bewit/Downloads/sudoku-solver-master/sudoku_solver.py", line 14, in <module>
    model = load_model('model/EnglishImg')
  File "C:\Users\bewit\miniconda3\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 149, in load_model
    loader_impl.parse_saved_model(filepath)
  File "C:\Users\bewit\miniconda3\lib\site-packages\tensorflow_core\python\saved_model\loader_impl.py", line 83, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: model/EnglishImg/{saved_model.pbtxt|saved_model.pb}

Process finished with exit code 1
```

**Comment by avasid** [comment]
@bewithdhanu EnglishImg is a dataset, not a model. Extract the tgz archive in `/model` directory, which should result in a `/model/English` directory. After that, run the following script/code from the `/model` directory, 
```
import os
from shutil import copy
dirs = sorted(os.listdir("./English/Img/GoodImg/Bmp/"))[1:10]
os.makedirs("./data", exist_ok=True)
for i,dir in enumerate(dirs,1):
    i = str(i)
    os.makedirs(os.path.join("./data",i),exist_ok=True)
    dir_path = os.path.join("./English/Img/GoodImg/Bmp/",dir)
    files = os.listdir(dir_path)
    for fil in files:
        copy(os.path.join(dir_path,fil),os.path.join("./data",i))
```

This should result in a `data` folder in `/model`. Now first run `train_char74k.py` which will train and save a model. And then run `sudoku_solver.py`.

**Comment by waxpancake** [comment]
FYI, I was able to use train_char74k.py for training, but needed to change the reference to "val_acc" to "val_accuracy" with my version of TensorFlow.

**Comment by addadda023** [comment]
> @bewithdhanu EnglishImg is a dataset, not a model. Extract the tgz archive in `/model` directory, which should result in a `/model/English` directory. After that, run the following script/code from the `/model` directory,
> 
> ```
> import os
> from shutil import copy
> dirs = sorted(os.listdir("./English/Img/GoodImg/Bmp/"))[1:10]
> os.makedirs("./data", exist_ok=True)
> for i,dir in enumerate(dirs,1):
>     i = str(i)
>     os.makedirs(os.path.join("./data",i),exist_ok=True)
>     dir_path = os.path.join("./English/Img/GoodImg/Bmp/",dir)
>     files = os.listdir(dir_path)
>     for fil in files:
>         copy(os.path.join(dir_path,fil),os.path.join("./data",i))
> ```
> 
> This should result in a `data` folder in `/model`. Now first run `train_char74k.py` which will train and save a model. And then run `sudoku_solver.py`.

Hi, what validation loss are you getting? The lenet model doesn't get better than 0.8 validation accuracy despite trying multiple augmentation and dropout methods. The end result is the model performs poorly when identifying the digits. 

![image](https://user-images.githubusercontent.com/19193308/89139102-86fb1f00-d4f2-11ea-9d57-f9cd7588bb0c.png)

Btw I changed the validation data to un-augmented images, as it should be. 
```
# Start training
H = model.fit_generator(X_datagen.flow(X_train, y_train, batch_size=32),
                        validation_data = (X_val, y_val),
                        callbacks = [cp_1, cp_2], steps_per_epoch = len(X_train) / 32,
                        epochs = 500)
```

**Comment by ngtrphuong** [comment]
The trained model did not work as expected,
The digit recognizer works quite messy,
